services:
  db:
    image: postgres:18.0-alpine
    restart: always
    container_name: application_name_db
    environment:
      POSTGRES_DB: application_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: main_application
    ports:
      - "8080:8080"
    depends_on:
      - db